# Pour l'environnement de production
# FROM node:16-alpine as build
# WORKDIR /app
# COPY package.json angular.json tsconfig.json tsconfig.app.json ./
# COPY src/ ./src/
# RUN npm install
# RUN npm run build
# FROM nginx:alpine
# # On suppose que le nom de projet généré est "front-angular"
# COPY --from=build /app/dist/front-angular /usr/share/nginx/html
# EXPOSE 80
# CMD ["nginx", "-g", "daemon off;"]


# Pour l'environnement de développement
FROM node:16-alpine
WORKDIR /app
COPY package.json angular.json tsconfig.json tsconfig.app.json ./
COPY src/ ./src/
RUN npm install
CMD ["npx", "ng", "serve", "--host", "0.0.0.0", "--port", "4200"]

