services:
  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    restart: unless-stopped

  qdrant:
    image: qdrant/qdrant
    ports:
      - "6333:6333"
    restart: unless-stopped

  agent_logic:
    build: ./agent_logic
    ports:
      - "5000:5000"
    depends_on:
      - ollama
      - qdrant
    environment:
      - OLLAMA_API_URL=http://ollama:11434
      - QDRANT_HOST=qdrant
      - QDRANT_PORT=6333
    restart: unless-stopped




  front_angular:
    build: ./front_angular
    ports:
      - "4200:4200"
    volumes:
      - ./front_angular/src:/app/src
      - ./front_angular/package.json:/app/package.json
      - ./front_angular/angular.json:/app/angular.json
      - ./front_angular/tsconfig.json:/app/tsconfig.json
      - ./front_angular/tsconfig.app.json:/app/tsconfig.app.json
    depends_on:
      - agent_logic
    restart: unless-stopped


